name = "web-multisite"

[web]
driver = "default"
host = "0.0.0.0"
port = 8090
domain = "demo.local"

[site.www]
alias = ["www1", "home"]

[site.file]
alias = ["fs", "cdn"]

[site.api]
alias = ["openapi", "gateway"]
